name: Installers

on: [push, pull_request]

env:
  # Java version to use in the Jitsi Desktop jars
  INSTALLER_JAVA_VERSION: 11

jobs:
  version:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Parse version
        id: parse
        run: |
          MVNVER=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
          MVNVER_MATCHER="^([0-9]+)\.([0-9]+)(\.([0-9]+))?(\.([0-9]+))?(-([A-Za-z0-9-]+))?"
          if [[ $MVNVER =~ $MVNVER_MATCHER ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            SUFFIX=${BASH_REMATCH[8]}
            echo "::set-output name=jitsi_version_major::${MAJOR}"
            echo "::set-output name=jitsi_version_minor::${MINOR}"
            echo "::set-output name=jitsi_version_rev::${SUFFIX}"
          else
            echo "$MVNVER did not match $MVNVER_MATCHER"
            exit 1
          fi;

          GITVER=`git describe --match Jitsi-[0-9.]* --long --dirty --always`
          echo "::set-output name=jitsi_version_git::${GITVER}"
          GITVER_MATCHER="^((Jitsi-[0-9.]+)-([0-9]+)-)?([A-Za-z0-9-]+)$"
          if [[ $GITVER =~ $GITVER_MATCHER ]]; then
            NCOMMITS=${BASH_REMATCH[3]}
            HASH=${BASH_REMATCH[4]}
            echo "::set-output name=jitsi_version_ncommits::${NCOMMITS}"
            echo "::set-output name=jitsi_version_hash::${HASH}"
          else
            echo "$GITVER did not match $GITVER_MATCHER"
            exit 1
          fi;

          VERSION_SHORT="${MAJOR}.${MINOR}.${NCOMMITS}"
          if [[ "$SUFFIX" == "" ]]; then
            VERSION_FULL="${VERSION_SHORT}+${HASH}"
          else
            VERSION_FULL="${VERSION_SHORT}-${SUFFIX}+${HASH}"
          fi;
          echo "::set-output name=jitsi_version_short::${VERSION_SHORT}"
          echo "::set-output name=jitsi_version_full::${VERSION_FULL}"

  deb:
    name: Ubuntu ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: version
    strategy:
      matrix:
        arch: [ x86, x64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.INSTALLER_JAVA_VERSION }}

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Java
        run: mvn -B -DskipTests package

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Build deb
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PW }}
        run: |
          cd $GITHUB_WORKSPACE/resources/install
          ./gradlew --no-daemon signDeb -Papplication.target=${{ matrix.arch }} -PgitVersion=${{ needs.version.outputs.jitsi_version_git }}

      - name: Upload deb
        uses: actions/upload-artifact@v2
        with:
          name: jitsi-debian-${{ matrix.arch }}
          path: resources/install/build/distributions/

  wix:
    name: Windows ${{ matrix.arch }}
    runs-on: windows-latest
    needs: version
    strategy:
      matrix:
        arch: [ x86, x64 ]
    steps:
      - name: Expand architecture
        id: expand_arch
        shell: bash
        run: |
          if [ "${{ matrix.arch }}" == "x86" ]; then
            echo "::set-output name=cmake_arch::Win32"
          else
            echo "::set-output name=cmake_arch::x64"
          fi;

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.INSTALLER_JAVA_VERSION }}

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Java
        run: mvn -B -DskipTests package

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Build natives
        run: |
          cd $Env:GITHUB_WORKSPACE/native/windows
          cmake -B cmake-build-${{ matrix.arch }} -A ${{ steps.expand_arch.outputs.cmake_arch }}
          cmake --build cmake-build-${{ matrix.arch }} --config Release

      - name: Upload CMake logs on failure
        if: ${{ failure() }}
        run: Compress-Archive -Path $Env:GITHUB_WORKSPACE/native/windows/src/native/cmake-build-${{ matrix.arch}} -DestinationPath $Env:GITHUB_WORKSPACE/debug-logs.zip

      - name: Upload Debug logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: win-${{ matrix.arch }}-debug
          path: debug*

      - name: Build installer
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/resources/install
          ./gradlew --no-daemon windowsZip signMsi -Papplication.target=${{ matrix.arch }} -PgitVersion=${{ needs.version.outputs.jitsi_version_git }}

      - name: Upload msi
        uses: actions/upload-artifact@v2
        with:
          name: jitsi-win-${{ matrix.arch }}
          path: |
            resources/install/build/install/wix/jitsi-*.msi
            resources/install/build/distributions/jitsi-*.zip

  mac:
    runs-on: macos-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.INSTALLER_JAVA_VERSION }}

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Java
        run: mvn -B -DskipTests package

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Build natives
        run: |
          cd $GITHUB_WORKSPACE/native/macosx
          cmake -B cmake-build
          cmake --build cmake-build --config Release --verbose

      - name: Generate dmg
        run: |
          cd $GITHUB_WORKSPACE/resources/install
          ./gradlew --no-daemon createDmg -PgitVersion=${{ needs.version.outputs.jitsi_version_git }}

      - name: Upload dmg
        uses: actions/upload-artifact@v2
        with:
          name: jitsi-mac
          path: resources/install/build/install/jitsi.dmg
