name: Installers

on: [push, pull_request]

jobs:
  java:
    name: Build with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0

      - name: Show version
        run: git describe --match "Jitsi-[0-9\.]*" --long --dirty --always

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Java source with Maven
        run: |
          mvn -B verify -DperformRelease=true  -DskipTests
